### ISSUE TITLE
Use_case_II: table access value error - don't match HEASARC table

### ISSUE THREAD

**Issue by abasuzych** [NASA-NAVO/navo-workshop#39]
The flux, flux_lower_flux_upper values for the table chansngcat have values ~ 1e-12 but the TAP service output gives as zero. Is this a rounding error? column format error? Note: the log_lx, log_lx_upper, log_lx_lower do match the HEASARC table from Browse and therefore this isn't a problem reading and accessing the data values for all the columns, but the one we use in the notebook!

**Comment by trjaffe** [comment]
Fixed at HEASARC.  (Our TAP service was returning a VOTable with an incorrect format of "5" instead of "E5".  The value was correct but the astropy table display uses that format and the result of 1e-12 in format of "5" is five digits after the decimal instead of 5 digits after the decimal *in scientific notation*.)

**Comment by bsipocz** [comment]
AAS240 workshop participant reported this, so I reopen this issue while we figure out what went wrong.

**Comment by bsipocz** [comment]
I haven't dug deep enough yet but losing the units is another issue here: Shall we report it upstream instead and close this issue again? I see this in cell5 of the notebook:

```
>>> tap_services[0].service.run_async(query)

<Table length=1>
   ra     dec    exposure   flux  flux_lower flux_upper
float64 float64  float64  float64  float64    float64  
------- -------- -------- ------- ---------- ----------
53.4019 -36.1407  15500.0     0.0        0.0        0.0



>>> tap_services[0].service.run_sync(query)

<Table length=1>
   ra       dec    exposure    flux    flux_lower flux_upper
  deg       deg       s     erg/s/cm^2 erg/s/cm^2 erg/s/cm^2
float64   float64  float64   float64    float64    float64  
-------- --------- -------- ---------- ---------- ----------
53.40192 -36.14067    15500  7.751e-12 7.1727e-12 8.2075e-12
```

**Comment by MGibb** [comment]
There seems to be an issue with how the HEASARC is returning sync vs async TAP queries.  The async queries are changing all of the results to something like ``<FIELD datatype="double" name="flux"/>`` where the sync queries are showing ``<FIELD unit="erg/s/cm^2" datatype="double" ucd="phot.flux;em.X-ray" precision="E5" name="flux">
<DESCRIPTION>Observed Flux in 2-10keV</DESCRIPTION>
</FIELD>`` for the same thing.  So both the units and precision are being removed.

**Comment by trjaffe** [comment]
Apologies for muddying the waters with sync vs async results.  But at least that means there’s a simple way to avoid the issue while we fix our end.

**Comment by trjaffe** [comment]
@MGibb Can you confirm whether or not this fix has been deployed already? This is issue 94 on Xamin, which has an August release as a milestone, so I guess not quite yet?

**Comment by MGibb** [comment]
@trjaffe I don't think it's been deployed yet.  I just checked and it looks like problem is still there.  The fix has been merged, so it should be fixed when the next update it released.

**Comment by trjaffe** [comment]
Fix was deployed.
